create database jynsge;

use jynsge;


show tables from jynsge;

select * from usuario;
select * from noticia;

create table usuario(
   id int not null primary key auto_increment,
   nome varchar(120),
   email varchar(100),
   senha int,
   dataCriacao timestamp,
   idComentario int not null
)engine = InnoDB;
drop table usuario;

create table noticia(
	id int not null primary key auto_increment,
    titulo varchar(250),
    linkImg varchar(500),
    conteudo Text not null, 
    resumo varchar(500), 
    user_id int not null, 
    dtPublicacao timestamp
)engine = InnoDB;

select *from noticia;

CREATE TABLE categoria (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao varchar(350),
    dataCriacao timestamp
) ENGINE = InnoDB;

CREATE TABLE noticiaCategoria (
	id int primary key not null auto_increment,
    idNoticia INT NOT NULL,
    idCategoria INT NOT NULL,
    FOREIGN KEY (idNoticia) REFERENCES noticia(id) ON DELETE CASCADE,
    FOREIGN KEY (idCategoria) REFERENCES categoria(id) ON DELETE CASCADE
) ENGINE = InnoDB;


create table comentario(
	id int not null primary key auto_increment,
    conteudo varchar(250),
    dataPublicacao timestamp,
    idNoticia int not null,
    idUsuario int not null,
	FOREIGN KEY (idNoticia) REFERENCES noticia(id) ON DELETE CASCADE,
    FOREIGN KEY (idCategoria) REFERENCES categoria(id) ON DELETE CASCADE
)engine = InnoDB;

create table perfil(
	id int not null primary key auto_increment,
	biografia text,
	linkImg varchar(500),
    tipoUsuario boolean not null,
    idUsuario int not null,
	FOREIGN KEY (idUsuario) REFERENCES usuario(id) ON DELETE CASCADE
)engine = InnoDB;


select * from users; -- visualizar todas as colunas da tabela com os 
select * from noticias; -- visualizar todas as colunas da tabela com os 

drop table usuario; -- apaga a tabela inteira
drop table perfil; -- apaga a tabela inteira
drop table noticia; -- apaga a tabela inteira
drop table comentario; -- apaga a tabela inteira



  
  insert into categorias (nome, descricao)
  values ('Internet', 'Em nenhum outro lugar você pode ver o quadro completo de como a tecnologia sem fio de amanhã a tecnologia está transformando a eficiência, elevando as experiências do usuário e nos impulsionando rumo a um mundo totalmente conectado.'),
  ('Acessibilidade', 'Descubra como avanços como assistentes de IA, dispositivos domésticos inteligentes, ativação por voz, mudanças no design inclusivo e muito mais estão melhorando a vida das pessoas com habilidades diferentes.'),
  ('AR/VR/XR','As tecnologias que transformaram os jogos estão agora mudando o jogo em outras indústrias e remodelando a forma como as empresas operam em todo o mundo.'),
  ('Inteligência Artificial','Indústrias em transformação. Abrindo novos recursos. Melhorando a eficiência. A inteligência artificial já está melhorando nossas vidas de maneiras profundas – e as possibilidades para o futuro são aparentemente ilimitadas.'),
  ('Conteúdo e Entretenimento','Saiba mais sobre as inovações que lideram a transformação do entretenimento, no lugar onde se reúnem marcas que sabem gerar buzz.'),
  ('Saúde Digital', 'Explore os avanços mais recentes em IA, IoT, telessaúde e soluções de saúde digital. Essas tecnologias inovadoras estão remodelando a prestação de cuidados de saúde, melhorando os resultados dos pacientes e aumentando a eficiência operacional.'),
  ('Criptomoedas','No cenário financeiro atual, tecnologia é dinheiro. Este é o momento de abraçar a inovação como a nova moeda - e um investimento valioso no futuro bancário.'),
  ('Tecnologia Alimentar','Descubra as deliciosas possibilidades criadas pelas inovações na agricultura, segurança, nutrição, sabor, embalagem, sustentabilidade e muito mais, e saiba o que está por vir no futuro da alimentação.'),
  ('Jogos e Esportes','Entre no jogo e veja de perto a próxima geração de hardware, software e acessórios que melhoram a experiência do usuário.'),
  ('Robótica','Explore as tecnologias robóticas que melhoram a segurança, estabelecem metas de sustentabilidade ao nosso alcance e, em última análise, criam um mundo melhor.'),
  ('Casa Inteligente','Descubra as inovações que combinam perfeitamente conveniência, eficiência e consciência ecológica, redefinindo o que significa viver de forma inteligente.'),
  ('Tecnologia Espacial','Os avanços na tecnologia de exploração espacial estão melhorando a previsão do tempo, conectividade através de sistemas de satélite e muito mais.'),
  ('Eventos','Eventos de tecnologia são o palco onde o futuro ganha forma, conectando mentes inovadoras e impulsionando ideias que irão transformar o mundo.'),
  ('Tecnologia Veicular','Desde veículos autônomos e conectados até avanços no transporte aéreo, a tecnologia transformou a maneira como vivenciamos a mobilidade.'),
  ('Automação','Desde veículos autônomos e conectados até avanços no transporte aéreo, a tecnologia transformou a maneira como vivenciamos a mobilidade.');

insert into noticias (titulo, linkImg, conteudo, resumo, user_id)
values('O Impacto do 5G no Futuro das Cidades Inteligentes', 'noticias/cidades.jpg', 'O lançamento da tecnologia 5G está criando novas oportunidades para o desenvolvimento de cidades inteligentes em todo o mundo. Com velocidades de internet mais rápidas e latência extremamente baixa, o 5G promete transformar a maneira como as cidades operam, trazendo avanços significativos em áreas como mobilidade urbana, segurança e gestão de recursos.
Cidades como Nova York, Xangai e Londres estão sendo pioneiras na implementação do 5G, aproveitando essa tecnologia para melhorar o tráfego, otimizar o consumo de energia e até mesmo aprimorar os sistemas de segurança pública. Por exemplo, a integração de sensores de tráfego em tempo real e câmeras conectadas com a rede 5G está permitindo o monitoramento e controle de congestionamentos de forma mais eficiente, criando uma experiência mais fluida para os cidadãos.
Especialistas afirmam que, à medida que a infraestrutura 5G for se expandindo, mais cidades ao redor do mundo terão acesso a essas inovações. Com isso, a expectativa é de que o 5G não apenas otimize a vida urbana, mas também leve a melhorias em qualidade de vida, tornando as cidades mais sustentáveis e interconectadas.','Com velocidades de internet mais rápidas e latência extremamente baixa, o 5G promete transformar a maneira como as cidades operam, trazendo avanços significativos em áreas como mobilidade urbana, segurança e gestão de recursos.','1'),
('O 5G e o Avanço dos Veículos Autônomos: Como a Conectividade vai Redefinir a Mobilidade','noticias/5g.jpg', 'A implementação do 5G está acelerando o desenvolvimento e a adoção de veículos autônomos. Com sua alta capacidade de comunicação em tempo real e baixíssima latência, o 5G proporciona a infraestrutura necessária para que carros, caminhões e outros veículos autônomos possam se comunicar de forma mais eficiente com outros veículos, pedestres e infraestruturas urbanas.
Fabricantes de automóveis como Tesla, Waymo e Audi estão testando seus sistemas de condução autônoma em áreas onde o 5G já foi instalado, observando uma melhoria significativa na segurança e precisão dos veículos. A tecnologia permite que os veículos compartilhem dados em tempo real sobre condições de tráfego, obstáculos e até mesmo acidentes, tornando as viagens mais seguras e dinâmicas.
Além disso, a capacidade do 5G de lidar com grandes volumes de dados em tempo real abre a possibilidade de novos recursos, como veículos autônomos que podem tomar decisões instantâneas com base nas condições ambientais em constante mudança. A indústria automotiva acredita que a combinação de 5G e inteligência artificial pode ser a chave para a criação de um futuro mais seguro e eficiente no transporte.','A implementação do 5G está acelerando o desenvolvimento e a adoção de veículos autônomos. Com sua alta capacidade de comunicação em tempo real e baixíssima latência, o 5G proporciona a infraestrutura necessária para que carros, caminhões e outros veículos autônomos possam se comunicar de forma mais eficiente com outros veículos, pedestres e infraestruturas urbanas.','1'),
('Tecnologias Inovadoras Transformam a Acessibilidade para Pessoas com Deficiência Visual','noticias/visual.jpg','  A tecnologia está desempenhando um papel crucial na criação de soluções que tornam o mundo mais acessível para pessoas com deficiência visual. Com o avanço da inteligência artificial (IA) e da realidade aumentada (AR), novas ferramentas estão sendo desenvolvidas para ajudar deficientes visuais a navegar com mais autonomia e segurança.
Recentemente, uma startup de tecnologia lançou um dispositivo wearable que utiliza IA e sensores de proximidade para ajudar pessoas com deficiência visual a identificar obstáculos em seu caminho. O dispositivo, que se parece com um par de óculos, usa feedback tátil e sonoro para alertar o usuário sobre objetos ao redor, como móveis e paredes, proporcionando maior liberdade de locomoção em espaços públicos e privados.
 Além disso, empresas de tecnologia como o Google estão investindo em recursos de acessibilidade, como a função "Lookout", que usa a câmera do smartphone para identificar objetos e ler textos em voz alta, facilitando a interação com o ambiente para pessoas com baixa visão.
 Essas inovações estão quebrando barreiras, permitindo que pessoas com deficiência visual ganhem mais independência e participação ativa na sociedade.', 'A tecnologia está desempenhando um papel crucial na criação de soluções que tornam o mundo mais acessível para pessoas com deficiência visual. Com o avanço da inteligência artificial (IA) e da realidade aumentada (AR), novas ferramentas estão sendo desenvolvidas para ajudar deficientes visuais a navegar com mais autonomia e segurança.','1'),
 ('Acessibilidade Digital: Empresas Adotam Ferramentas para Incluir Pessoas com Deficiência no Ambiente Online', 'noticias/acess.jpg', '    Com a crescente digitalização dos serviços e da comunicação, a acessibilidade online tem se tornado uma prioridade para muitas empresas, com o objetivo de garantir que pessoas com deficiência possam acessar websites e aplicativos com facilidade.
 Uma tendência crescente é o uso de tecnologias como o reconhecimento de voz, transcrição automática e leitores de tela, que permitem que pessoas com deficiência auditiva e visual acessem conteúdo de forma mais inclusiva. Além disso, plataformas como a Microsoft estão implementando recursos de acessibilidade mais avançados em seus sistemas operacionais, como o "Narrador", um leitor de tela embutido que lê o conteúdo da tela em voz alta.
Além de ferramentas específicas, empresas estão cada vez mais se comprometendo a seguir as Diretrizes de Acessibilidade para Conteúdo Web (WCAG) para garantir que seus sites e plataformas sejam compatíveis com tecnologias assistivas. No ano passado, a Amazon e o Facebook lançaram atualizações significativas em suas plataformas, tornando-as mais inclusivas para deficientes visuais, auditivos e motoros.
Com essas inovações, a tecnologia está desempenhando um papel essencial para garantir que todas as pessoas, independentemente de suas habilidades, possam participar ativamente da sociedade digital.','Com a crescente digitalização dos serviços e da comunicação, a acessibilidade online tem se tornado uma prioridade para muitas empresas, com o objetivo de garantir que pessoas com deficiência possam acessar websites e aplicativos com facilidade.', '1'),
('Siemens e NVIDIA fazem parceria para construir o Metaverso Industrial', 'noticias/meta.webp', 'A Siemens, líder em automação industrial, software, infraestrutura, tecnologia de construção e transporte, e a NVIDIA, pioneira em aceleração gráfica e inteligência artificial (IA), anunciaram a ampliação de sua parceria com o objetivo de viabilizar o metaverso industrial e expandir o uso de digital twins impulsionados pela IA, elevando a automação industrial a novos patamares.
A integração da Siemens Xcelerator com a plataforma NVIDIA Omniverse permitirá criar um ambiente colaborativo em 3D, onde modelos digitais da Siemens e IA em tempo real da NVIDIA ajudarão as empresas a tomar decisões mais rápidas e confiantes. Isso acelerará a adoção de digital twins, melhorando a produtividade e os processos ao longo dos ciclos de vida dos produtos e facilitando o desenvolvimento de soluções inovadoras em IoT e análises em tempo real.', ' O Metaverso Industrial será um lugar onde inovaremos na velocidade do software. Ele oferecerá enorme potencial para transformar nossas economias e indústrias.','1'),
('Automação e Tecnologia: Como essa relação pode beneficiar sua indústria?','noticias/auto.jpg', 'A automação e a tecnologia estão transformando o setor industrial, oferecendo benefícios como maior eficiência, redução de custos e melhoria na qualidade. Ao automatizar processos, as empresas podem otimizar recursos, reduzir erros e aumentar a produtividade. Além disso, o uso de tecnologias avançadas, como análise de dados em tempo real, possibilita decisões mais informadas e rápidas.
A flexibilidade e escalabilidade das soluções tecnológicas permitem às indústrias se adaptarem rapidamente às mudanças do mercado. A segurança no ambiente de trabalho também melhora, com a automação de tarefas perigosas. Com a inovação constante, a automação abre espaço para novos produtos e soluções mais competitivas, ao mesmo tempo em que contribui para práticas empresariais mais sustentáveis.
Em resumo, a adoção de automação e tecnologia é essencial para indústrias que buscam se manter competitivas, eficientes e preparadas para o futuro.', 'A automação e a tecnologia estão transformando o setor industrial, oferecendo benefícios como maior eficiência, redução de custos e melhoria na qualidade','1'),
(' Carros Autônomos Avançam em Testes de Condução em Ambientes Complexos','noticias/car.jpeg','Os carros autônomos estão dando um passo importante para a integração total no trânsito das cidades. Com o uso de inteligência artificial, sensores LiDAR, câmeras e radares, os veículos autônomos estão cada vez mais capazes de lidar com ambientes urbanos complexos, como interseções movimentadas, pedestres, ciclistas e mudanças imprevistas no tráfego. Empresas como Waymo (subsidiária do Google) e Tesla estão ampliando os testes de suas frotas em cidades de diferentes partes do mundo. A mais recente inovação inclui carros autônomos capazes de operar de forma independente em condições climáticas adversas, como chuva ou neve, o que representa um grande avanço na segurança e confiabilidade desses veículos. A perspectiva de reduzir os acidentes causados por erro humano está acelerando o desenvolvimento dessa tecnologia.',' Os carros autônomos estão dando um passo importante para a integração total no trânsito das cidades','1'),
(' Carros Elétricos de Carga Rápida Transformam o Mercado de Mobilidade Sustentável','noticias/carro.jpeg','Os carros elétricos estão se tornando mais acessíveis e eficientes, e um dos maiores avanços nos últimos tempos é a tecnologia de recarga ultrarrápida. Novos carros elétricos estão sendo lançados com baterias que podem ser recarregadas até 80% em menos de 20 minutos, uma grande melhoria em relação às versões anteriores que demoravam horas para completar uma carga. Essa inovação, junto com o aumento de estações de recarga ultrarrápida, está tornando os veículos elétricos uma alternativa mais prática para quem precisa de maior autonomia e rapidez. Além disso, os avanços nas baterias, como as de estado sólido, prometem ainda mais eficiência e uma vida útil mais longa, consolidando o papel dos carros elétricos na luta contra as emissões de gases de efeito estufa e a poluição do ar nas grandes cidades.','Os carros elétricos estão se tornando mais acessíveis e eficientes, e um dos maiores avanços nos últimos tempos é a tecnologia de recarga ultrarrápida. ', '1'),
(' Segurança em Casas Inteligentes: Novos Sistemas de Monitoramento Usando IA e Câmeras de Alta Definição', 'noticias/camera.jpeg', 'A segurança em casas inteligentes está evoluindo com o uso de inteligência artificial (IA) e câmeras de alta definição. Novos sistemas de monitoramento são capazes de reconhecer rostos, detectar movimentos suspeitos e até analisar padrões de comportamento para identificar atividades incomuns, como uma janela sendo aberta em um horário não habitual ou a presença de pessoas em áreas restritas da casa. Além disso, esses sistemas agora oferecem alertas em tempo real para os moradores, permitindo que eles monitorem suas casas remotamente por meio de smartphones. Com a implementação de IA, os sistemas de segurança podem aprender a diferenciar entre atividades normais e possíveis ameaças, reduzindo os falsos alarmes e melhorando a eficácia da proteção.', 'A segurança em casas inteligentes está evoluindo com o uso de inteligência artificial (IA) e câmeras de alta definição.','1'),
('  Assistentes Virtuais Evoluem para Gerenciar Casas Inteligentes de Forma Integrada', 'noticias/casa.jpeg', '   Os assistentes virtuais, como Alexa, Google Assistant e Siri, estão se tornando ainda mais sofisticados, permitindo um controle total e integrado das casas inteligentes. Com a capacidade de gerenciar desde iluminação, temperatura e segurança até aparelhos de cozinha e entretenimento, esses assistentes agora podem aprender com os hábitos dos moradores e antecipar suas necessidades. Por exemplo, um assistente pode ajustar a temperatura automaticamente com base na hora do dia ou no clima, ou até mesmo configurar um ambiente perfeito para assistir a um filme, ajustando as luzes e o som. Com a crescente integração de dispositivos IoT (Internet das Coisas), as casas inteligentes estão se tornando mais autônomas, oferecendo um nível de conveniência e personalização sem precedentes.', ' Os assistentes virtuais, como Alexa, Google Assistant e Siri, estão se tornando ainda mais sofisticados, permitindo um controle total e integrado das casas inteligentes.','1');
                                                                                              
                                                                                                   
insert into noticias (titulo, linkImg, conteudo, resumo, user_id, published_at)
values('Impressão 3D Transforma a Produção de Alimentos Personalizados','noticias/alimen.jpeg','  A tecnologia de impressão 3D está revolucionando a indústria alimentícia, permitindo a criação de alimentos personalizados e inovadores. Empresas estão utilizando impressoras 3D para fabricar alimentos com formatos e texturas complexas, além de criar produtos mais sustentáveis e eficientes. Um exemplo disso são as "carne impressas", criadas a partir de proteínas vegetais, que oferecem uma alternativa mais ecológica à carne tradicional. Além disso, a impressão 3D também está sendo utilizada para adaptar refeições de acordo com as necessidades dietéticas específicas de cada indivíduo, como alergias alimentares ou restrições nutricionais, oferecendo uma maneira mais precisa e criativa de atender às demandas de consumidores modernos.','A tecnologia de impressão 3D está revolucionando a indústria alimentícia, permitindo a criação de alimentos personalizados e inovadores.','1','2025-01-01 17:30:00');
   
   
insert into noticias (titulo, linkImg, conteudo, resumo, user_id, published_at)
values('Tecnologia de Cultivo Celular Promete Revolucionar a Produção de Carne','noticias/carne.jpeg','          A produção de carne cultivada em laboratório, ou carne celular, está se tornando uma das inovações mais promissoras no setor alimentar. Utilizando biotecnologia, cientistas conseguem cultivar células animais em ambiente controlado para criar carne sem a necessidade de abate. Essa tecnologia promete não apenas reduzir o impacto ambiental da produção de carne tradicional, como também minimizar o uso de recursos naturais e melhorar a sustentabilidade do setor alimentar. Empresas como a Impossible Foods e a Eat Just já estão investindo nessa área, e alguns países, como Cingapura, já aprovaram a comercialização de carne cultivada. Essa mudança pode ser um passo significativo para resolver problemas globais como a escassez de alimentos e a preservação ambiental.',' A produção de carne cultivada em laboratório, ou carne celular, está se tornando uma das inovações mais promissoras no setor alimentar.','1','2025-01-01 17:30:00'),
('Bitcoin Atinge Novo Recorde de Adoção Corporativa e Institucional','noticias/bit.webp','        Em 2025, o Bitcoin alcançou um novo marco de adoção, com grandes empresas e instituições financeiras integrando a criptomoeda em suas operações. Empresas como Tesla e MicroStrategy continuam a aumentar suas reservas de Bitcoin, enquanto bancos de investimento como Goldman Sachs e JPMorgan começaram a oferecer produtos relacionados a criptomoedas para seus clientes. Além disso, várias nações estão discutindo a possibilidade de adotar o Bitcoin como uma moeda oficial ou usá-lo como reserva estratégica, o que tem levado a criptomoeda a atingir novos patamares de valorização. Esse movimento pode sinalizar um ponto de inflexão em que as criptomoedas deixam de ser vistas apenas como ativos especulativos, tornando-se cada vez mais parte do sistema financeiro global.',' Em 2025, o Bitcoin alcançou um novo marco de adoção, com grandes empresas e instituições financeiras integrando a criptomoeda em suas operações.','1', '2025-01-01 17:30:00'),
 (' Ethereum Introduz Atualização de Escalabilidade com Ethereum 2.0','noticias/ethe.jpeg', ' A rede Ethereum passou a implementar a tão aguardada atualização Ethereum 2.0, uma série de melhorias técnicas que buscam resolver problemas de escalabilidade e sustentabilidade do blockchain. Uma das mudanças mais significativas é a transição do modelo de consenso de Proof of Work (PoW) para Proof of Stake (PoS), o que promete reduzir o consumo de energia e aumentar a eficiência das transações na rede. Com a atualização, espera-se que Ethereum possa suportar um número maior de transações por segundo, além de tornar o processo mais seguro e acessível para desenvolvedores e investidores. Essa evolução pode consolidar ainda mais o Ethereum como a principal plataforma para contratos inteligentes e descentralização de serviços financeiros.', ' A rede Ethereum passou a implementar a tão aguardada atualização Ethereum 2.0, uma série de melhorias técnicas que buscam resolver problemas de escalabilidade e sustentabilidade do blockchain.','1', '2025-01-01 17:30:00'),
 (' MWC2025 Barcelona', 'noticias/mwc.webp','O MWC 2025 (Mobile World Congress 2025) será um dos maiores eventos globais de tecnologia, focado em inovações no setor de mobilidade, telecomunicações e dispositivos móveis. Tradicionalmente realizado anualmente em Barcelona, o MWC reúne empresas líderes de todo o mundo para apresentar as últimas novidades e tendências em tecnologia móvel, como smartphones, 5G, inteligência artificial (IA), Internet das Coisas (IoT), realidade aumentada (AR), realidade virtual (VR), entre outras.  O MWC 2025 será um evento imperdível para aqueles interessados em acompanhar o futuro das telecomunicações e da tecnologia móvel, com o evento acontecendo no Centro de Convenções Fira Gran Via, em Barcelona. A agenda provavelmente incluirá debates sobre a evolução do 5G para o 6G, avanços em IA, dispositivos conectados e inovações em mobilidade e infraestrutura digital. Interessados podem comprar os ingressos no site oficial https://www.mwcbarcelona.com/', 'Coisas incríveis já estão em andamento no maior e mais influente evento de conectividade do mundo. 3  a  6  de março  de 2025 Fira Gran Vía, Barcelona','1', '2025-01-01 17:30:00'),
 (' Web Summit Rio 2025','summit.jpg', 'O Web Summit Rio faz parte de uma série de eventos internacionais organizados pela empresa, ao lado do Web Summit em Lisboa, Web Summit Qatar em Doha, Collision em Toronto e RISE em Hong Kong. Em 2024, o Web Summit Rio reuniu mais de 34.000 pessoas no Riocentro, e no próximo ano, o evento retornará ao Rio de Janeiro para mais uma edição histórica. Para saber mais acesse https://rio.websummit.com/','De 27 a 30 de abril de 2025, o Rio de Janeiro será o palco do Web Summit Rio 2025, um dos maiores eventos de tecnologia e inovação do mundo. Tradicionalmente realizado em Lisboa, o Web Summit agora também conta com uma edição no Brasil, se consolidando como um importante ponto de encontro para a comunidade global de tecnologia.','1', '2025-01-01 17:30:00'),
 ('Google introduz "marca dágua" para sinalizar conteúdo gerado por IA.', 'noticias/google.webp','  Em um esforço para garantir o uso seguro e responsável da IA, grandes empresas de tecnologia, como Google, Microsoft e Amazon, assinaram um acordo voluntário nos EUA comprometendo-se a adicionar marcas dágua em conteúdos gerados por IA. A medida visa aumentar a transparência e ajudar na identificação de imagens e vídeos criados por algoritmos. A Meta também segue a tendência, implementando marcas dágua em seu novo gerador de vídeos. Enquanto isso, na China, o uso de marcas dágua em criações de IA é agora obrigatório, com empresas como Alibaba já adotando a prática. A necessidade de padronização e coordenação entre as empresas é um tema central, com especialistas destacando a importância de monitorar os impactos dessas iniciativas.','Em um esforço para garantir o uso seguro e responsável da IA, grandes empresas de tecnologia, como Google, Microsoft e Amazon, assinaram um acordo voluntário nos EUA comprometendo-se a adicionar marcas dágua em conteúdos gerados por IA.', '1', '2025-01-01 17:30:00'),
 ('IA auxilia na detecção precoce de um tipo comum de arritmia cardíaca', 'noticias/medico.jpg', ' Iniciado em 2023, o projeto de inovação aberta com o uso de IA tem como objetivo identificar precocemente e tratar pacientes com fibrilação atrial em um modelo de cuidado digitalizado. Raphael Oliveira, diretor-geral do Hospital Nove de Julho, explica à CNN que a fibrilação atrial, além de ser a arritmia mais frequente, tem se tornado mais prevalente com o envelhecimento da população, impactando a qualidade de vida dos pacientes e aumentando o risco de problemas cardíacos e acidentes vasculares cerebrais (AVC).
Com um ano de implementação, o uso da IA no projeto resultou em um aumento de 82,3% no número de pacientes tratados para fibrilação atrial, uma melhoria de 30% na qualidade de vida dos pacientes acompanhados e uma redução de 43 pontos percentuais na procura por pronto-socorro em pacientes monitorados durante um período de 30 dias.','Um projeto brasileiro que utiliza inteligência artificial (IA) para a detecção de arritmias cardíacas foi premiado com o Gartner Eye on Innovation 2024, um importante reconhecimento global de inovação, em outubro. Desenvolvido pelo Hospital Nove de Julho, em colaboração com a Johnson & Johnson MedTech e a startup Neomed, o projeto resultou em um aumento de 82,3% no número de pacientes tratados para fibrilação atrial na instituição. Essa condição é o tipo mais comum de arritmia cardíaca, afetando cerca de 2,5% da população, segundo a Sociedade Brasileira de Cardiologia (SBC).','1''2025-01-01 17:30:00'),
('Após 25 anos, a Intel será substituida pela Nvidea', 'noticias/intel.jpg',' A Nvidia, gigante de chips no epicentro da revolução da inteligência artificial, será incluída no prestigiado índice Dow Jones, substituindo a rival Intel a partir de 8 de novembro. A inclusão da Nvidia no índice de blue chips reflete o impacto do crescimento impulsionado pela IA, que fez o valor da empresa disparar 900% nos últimos dois anos. O Dow Jones era o único grande índice de ações dos EUA a não ter a Nvidia entre suas componentes. 
 A Intel, que foi adicionada ao Dow Jones em novembro de 1999, junto com empresas como Microsoft, SBC e Home Depot, deixa o índice após 25 anos. No entanto, a Intel tem enfrentado desafios recentes, com um plano de reestruturação que inclui redução de gastos, cortes de empregos e suspensão de dividendos. Suas ações caíram 54% em 2024, e caíram mais 2% após o fechamento da última sexta-feira. Nos últimos quatro anos, a Intel também passou por duas divisões de suas ações, sendo a mais recente em junho, quando cada ação foi dividida por dez. 
 Apesar da diminuição da influência do Dow ao longo do tempo, à medida que os investidores se orientam por índices baseados em valor de mercado, o índice ainda se mantém como um dos principais termômetros da força econômica dos Estados Unidos.',' A Nvidia, gigante de chips no epicentro da revolução da inteligência artificial, será incluída no prestigiado índice Dow Jones, substituindo a rival Intel a partir de 8 de novembro.','1','2025-01-01 17:30:00'),
 ('Presidente do SoftBank afirma que a superinteligência artificial poderá existir até 2035.','noticias/super.webp', ' O presidente-executivo do SoftBank Group, Masayoshi Son, reafirmou nesta terça-feira (29) sua convicção de que a superinteligência artificial (ASI) será uma realidade em breve, destacando que isso exigirá investimentos de centenas de bilhões de dólares. Durante uma conferência em Riad, na Arábia Saudita, ele afirmou que a ASI será 10 mil vezes mais inteligente do que o cérebro humano e deverá surgir até 2035.
 Son mencionou que está reservando recursos "para dar o próximo grande passo", embora não tenha revelado detalhes sobre seus planos de investimento. Ele também previu que a IA generativa demandará um investimento acumulado de 900 trilhões de dólares em data centers e chips, destacando que acredita que a fabricante de chips Nvidia está subvalorizada com base nessa projeção. <br>Reconhecido por suas apostas bem-sucedidas em tecnologias inovadoras, como a internet móvel e o comércio eletrônico, Son também tem um histórico misto como investidor. O lançamento dos Vision Funds do SoftBank, em 2017, causou grande impacto no capital de risco, mas muitas das startups apoiadas por esses fundos sofreram uma queda significativa em seu valor. Até o final de junho de 2024, os Vision Funds registraram uma perda de 2,4 bilhões de dólares. ','O presidente-executivo do SoftBank Group, Masayoshi Son, reafirmou nesta terça-feira (29) sua convicção de que a superinteligência artificial (ASI) será uma realidade em breve, destacando que isso exigirá investimentos de centenas de bilhões de dólares.','1', '2025-01-01 17:30:00'),
 ('E-Sports: A Ascensão das Ligas Profissionais e o Uso de IA para Análise de Jogos','noticias/analise.jpeg','Os e-sports continuam a crescer como um setor de entretenimento de bilhões de dólares, com ligas profissionais sendo estabelecidas ao redor do mundo. Um dos maiores avanços nos jogos eletrônicos competitivos é a utilização de inteligência artificial (IA) para analisar o desempenho dos jogadores. Ferramentas de IA estão sendo usadas para estudar estratégias, identificar padrões e prever movimentos, ajudando os treinadores a otimizar a preparação dos times. Além disso, a IA também é usada para melhorar a experiência do público, oferecendo análises ao vivo e insights detalhados durante as transmissões de torneios. O aumento da popularidade dos e-sports, combinado com inovações tecnológicas, está tornando o cenário ainda mais dinâmico e acessível para fãs e jogadores.',' Os e-sports continuam a crescer como um setor de entretenimento de bilhões de dólares, com ligas profissionais sendo estabelecidas ao redor do mundo.','1', '2025-01-01 17:30:00'),
 ('Tecnologia de Realidade Aumentada (RA) e Realidade Virtual (RV) Revoluciona o Treinamento de Atletas', 'noticias/atleta.jpeg', ' Atletas de elite estão utilizando tecnologias de realidade aumentada (RA) e realidade virtual (RV) para aprimorar seus treinos e melhorar o desempenho. Essas tecnologias permitem simulações de jogos e situações de alta pressão, oferecendo uma experiência imersiva sem os riscos físicos do treinamento convencional. Por exemplo, jogadores de futebol podem treinar suas habilidades de tomada de decisão em cenários virtuais realistas, enquanto pilotos de esportes motorizados praticam manobras em simuladores de RV. A RA também é usada para analisar movimentos e corrigir posturas em tempo real, aumentando a precisão dos treinamentos. Esse uso de tecnologia está proporcionando uma preparação mais eficiente, personalizada e segura para os atletas.', ' Atletas de elite estão utilizando tecnologias de realidade aumentada (RA) e realidade virtual (RV) para aprimorar seus treinos e melhorar o desempenho.','1','2025-01-01 17:30:00'),
 (' Elon Musk adia cronograma para OPTIMUS', 'noticias/optimus.jpg'	,'Elon Musk anunciou que o lançamento do robô humanoide Optimus, da Tesla, sofreu um pequeno atraso. Inicialmente esperado para começar a operar nas fábricas da Tesla em 2024, o robô agora deverá ser lançado apenas em 2025. E para os clientes que aguardavam ansiosos por um Optimus em casa, a espera será ainda mais longa, com as entregas previstas para 2026. <br> Por ser um projeto altamente ambicioso, um atraso não é algo inesperado. O Optimus, um robô projetado para realizar uma grande variedade de tarefas, enfrenta desafios técnicos complexos, especialmente devido à sua estrutura humanoide. Desenvolver um robô bípede é uma tarefa desafiadora, que exige muito mais do que simples modelos com rodas ou com múltiplos pontos de apoio.
Embora Elon Musk tenha prometido inicialmente que os primeiros robôs estariam operacionais até o final de 2024, ele ajustou suas previsões. Musk agora afirma que uma produção limitada de robôs estará disponível em 2025, com a produção em larga escala só sendo iniciada em 2026.', 'Elon Musk anunciou que o lançamento do robô humanoide Optimus, da Tesla, sofreu um pequeno atraso.','1','2025-01-01 17:30:00'),
(' A Clone Robotics revoluciona a tecnologia ao desenvolver um robô humanoide equipado com músculos artificiais, oferecendo movimentos mais naturais e ágeis.','noticias/torso.jpg','A Clone Robotics apresentou seu novo torso humanoide inovador, que promete transformar os padrões da robótica. De acordo com o Gadgets Nerds, o robô é equipado com músculos artificiais projetados para replicar os movimentos humanos, visando ser um dos primeiros (se não o primeiro) a oferecer movimentos fluídos e precisos.  Ao contrário dos robôs tradicionais, que possuem movimentos rígidos e mecânicos, este modelo se aproxima da sutileza e precisão dos gestos humanos, o que pode torná-lo uma ferramenta valiosa em áreas como a medicina, realizando procedimentos médicos, ou em tarefas que exigem montagens complexas de equipamentos que desafiam os limites físicos do ser humano.', 'A Clone Robotics apresentou seu novo torso humanoide inovador, que promete transformar os padrões da robótica.', '1','2025-01-01 17:30:00'),
(' Conheça o Iron: robô humanoide feito na China com 200 graus de liberdade', 'noticia/robo.webp',' A XPENG, fabricante chinesa de veículos elétricos, deu um passo importante ao apresentar o Iron, seu primeiro robô humanoide. Esse lançamento representa a expansão da empresa além do mercado automotivo, explorando novas frentes na robótica e inteligência artificial (IA), um movimento semelhante ao que a Tesla tem seguido. 
O Iron é equipado com mais de 60 articulações e 200 graus de liberdade, permitindo a execução de movimentos complexos com alta precisão. De acordo com a XPENG, a tecnologia por trás do robô é inspirada nos recursos já aplicados em seus veículos elétricos, destacando a convergência entre automação e robótica na empresa.
Realiza movimentos complexos e é alimentado pelo chip Turing AI, capaz de processar até 30 bilhões de parâmetros, simulando a flexibilidade humana. Com 1,75 m de altura e 70 kg, o robô já está sendo usado nas linhas de produção da XPENG, ajudando na montagem do P7+. O desempenho do Turing AI, que completou mais de 2.700 testes em 40 dias, coloca a XPENG em uma posição competitiva no mercado de robôs humanoides.', 'A XPENG, fabricante chinesa de veículos elétricos, deu um passo importante ao apresentar o Iron, seu primeiro robô humanoide.','1','2025-01-01 17:30:00'),
('  Projeto GR00T: NVIDIA aumentará  a destreza e mobilidade do robô com nova IA e ferramentas de simulação', 'noticias/groot.webp','A NVIDIA lançou o Projeto GR00T, um modelo-base de uso geral para robôs humanoides, com o objetivo de avançar nas inovações em robótica e IA. Juntamente com o GR00T, a empresa apresentou o Jetson Thor, um novo computador para robôs, baseado no sistema em um chip (SoC) NVIDIA Thor, e atualizações para a plataforma NVIDIA Isaac™, incluindo IA generativa e ferramentas de simulação. <br><br> O Jetson Thor oferece desempenho de IA de ponta, com 800 teraflops, e foi desenvolvido para permitir que os robôs aprendam habilidades como coordenação e adaptação ao interagir com o ambiente. A NVIDIA está colaborando com empresas líderes em robótica, como Boston Dynamics, XPENG Robotics e outras.','A NVIDIA lançou o Projeto GR00T, um modelo-base de uso geral para robôs humanoides, com o objetivo de avançar nas inovações em robótica e IA.','1','2025-01-01 17:30:00'),
('Inteligência Artificial Revoluciona Diagnóstico Médico com Mais Precisão.', 'noticias/sau.jpg',' A inteligência artificial (IA) tem ganhado cada vez mais destaque no campo da saúde, especialmente no diagnóstico de doenças. Algoritmos de aprendizado de máquina estão sendo treinados para analisar imagens médicas, como raios-X, ressonâncias magnéticas e tomografias, com uma precisão impressionante, frequentemente superando os diagnósticos feitos por médicos humanos. Além disso, a IA também está sendo usada para prever o risco de doenças em pacientes com base em seu histórico médico, hábitos de vida e dados genéticos, ajudando na detecção precoce de condições como câncer, doenças cardiovasculares e diabetes. Essa tecnologia está não só aumentando a precisão dos diagnósticos, mas também proporcionando tratamentos mais rápidos e eficazes.',' A inteligência artificial (IA) tem ganhado cada vez mais destaque no campo da saúde, especialmente no diagnóstico de doenças.','1','2025-01-01 17:30:00'),
('Tecnologia de Wearables Ajuda no Monitoramento Contínuo de Saúde','noticias/saude.jpg',' Dispositivos wearables, como relógios e pulseiras inteligentes, estão se tornando ferramentas essenciais para o monitoramento da saúde. Além de monitorar batimentos cardíacos e a quantidade de passos, esses dispositivos agora conseguem medir níveis de oxigênio no sangue, controlar padrões de sono e até detectar sinais de problemas cardíacos. Mais recentemente, as tecnologias vestíveis têm sido integradas a sistemas de saúde, permitindo que médicos acompanhem dados em tempo real e ajustem tratamentos de forma mais personalizada. Isso não só oferece mais autonomia para os pacientes, como também permite intervenções rápidas, muitas vezes prevenindo complicações sérias antes que se tornem emergências.','Dispositivos wearables, como relógios e pulseiras inteligentes, estão se tornando ferramentas essenciais para o monitoramento da saúde.','1','2025-01-01 17:30:00'),
('Tecnologia de Propulsão de Íons Promete Revolucionar Viagens Espaciais de Longa Distância','noticias/foguete.jpeg',' A propulsão de íons, uma tecnologia que utiliza correntes elétricas para acelerar partículas e gerar propulsão, está sendo cada vez mais explorada para missões espaciais de longa distância. Com um maior impulso específico e eficiência em comparação com os motores convencionais, essa tecnologia permite que espaçonaves viagem mais rápido e gastem menos combustível, sendo ideal para missões para os confins do sistema solar. A NASA, por exemplo, tem investido em propulsores iônicos para suas futuras missões a Júpiter e Saturno, bem como para a exploração de asteroides. A propulsão de íons poderia também abrir o caminho para viagens mais rápidas à Lua e até mesmo a Marte, acelerando o futuro das viagens interplanetárias.',' A propulsão de íons, uma tecnologia que utiliza correntes elétricas para acelerar partículas e gerar propulsão, está sendo cada vez mais explorada para missões espaciais de longa distância.','1','2025-01-01 17:30:00'),
(' Exploração de Marte Avança com Novos Robôs e Missões de Coleta de Amostras','noticias/marte.jpeg',' A exploração de Marte está ganhando novos avanços com o lançamento de missões de coleta de amostras e o desenvolvimento de robôs mais avançados. A NASA e outras agências espaciais, como a ESA (Agência Espacial Europeia), estão enviando novos rover e drones para estudar o solo marciano de maneira mais aprofundada. Uma das missões mais emocionantes é a coleta de amostras de solo e rochas para serem enviadas de volta à Terra. Esses materiais, que podem conter sinais de vida microbiana passada, são cruciais para entender a história do planeta vermelho e suas condições para suportar vida. Além disso, novas tecnologias de inteligência artificial estão ajudando os rovers a tomar decisões autônomas em tempo real, permitindo que realizem tarefas complexas de exploração sem a necessidade de comunicação constante com a Terra.',' A exploração de Marte está ganhando novos avanços com o lançamento de missões de coleta de amostras e o desenvolvimento de robôs mais avançados.','1','2025-01-01 17:30:00'),
(' Plataformas de Streaming Investem em Inteligência Artificial para Personalização de Conteúdo.', 'noticias/tv.jpg', ' As plataformas de streaming, como Netflix, Spotify e YouTube, estão cada vez mais utilizando inteligência artificial (IA) para oferecer recomendações mais precisas aos seus usuários. Com o avanço de algoritmos de aprendizado de máquina, essas plataformas conseguem entender melhor o gosto individual de cada usuário e sugerir filmes, séries e músicas que estejam alinhadas com suas preferências. Além disso, as IA também estão sendo usadas para otimizar a criação de conteúdo original, analisando tendências e comportamentos para prever o que pode fazer sucesso. Essa personalização vem gerando uma experiência de entretenimento mais envolvente e exclusiva, impactando diretamente o consumo de mídia global.',' Plataformas de streaming, como Netflix, Spotify e YouTube, estão cada vez mais utilizando inteligência artificial (IA) para oferecer recomendações mais precisas aos seus usuários.','1','2025-01-01 17:30:00'),
('Realidade Aumentada Transforma a Experiência de Jogos e Concertos ao Vivo','noticias/jogo.avif',' A realidade aumentada (RA) tem revolucionado a forma como consumimos entretenimento, especialmente no setor de jogos e eventos ao vivo. No universo dos jogos, desenvolvedores estão incorporando RA para criar experiências imersivas, onde o ambiente físico do jogador é integrado com elementos digitais. Isso está permitindo que jogadores interajam com personagens e cenários no mundo real, criando uma nova dimensão de jogabilidade. Já nos concertos ao vivo, a tecnologia de RA está sendo usada para enriquecer as apresentações, projetando efeitos visuais e interações digitais diretamente no palco, proporcionando uma experiência única para o público. A tendência tem ganhado força, atraindo tanto empresas de jogos quanto grandes artistas a explorar novas formas de engajar seus fãs.','A realidade aumentada (RA) tem revolucionado a forma como consumimos entretenimento, especialmente no setor de jogos e eventos ao vivo.', '1','2025-01-01 17:30:00'),
(' Realidade Aumentada Transforma o Setor de Vendas e Compras Online', 'noticias/ar.jpg', '
A Realidade Aumentada (AR) tem ganhado destaque nos últimos anos, especialmente no setor de e-commerce, permitindo uma experiência de compra mais interativa e personalizada. Grandes varejistas como IKEA e Amazon estão implementando ferramentas de AR que permitem aos consumidores visualizar produtos em seus próprios lares antes de realizar uma compra.
O aplicativo da IKEA, por exemplo, permite que os clientes usem a câmera de seus smartphones para ver como móveis e acessórios se encaixariam em seus espaços, ajustando tamanhos, cores e estilos em tempo real. A AR proporciona uma experiência mais imersiva, reduzindo a dúvida dos consumidores ao fazer escolhas de compra e diminuindo o número de devoluções.
Empresas de moda também estão utilizando AR para permitir que os clientes "experimentem" roupas e acessórios virtualmente, utilizando avatares digitais baseados nas suas medidas corporais. Com isso, a AR está não apenas facilitando o processo de compra, mas também criando novas formas de interação que unem o mundo físico e o digital de maneira intuitiva.', 'A Realidade Aumentada (AR) tem ganhado destaque nos últimos anos, especialmente no setor de e-commerce, permitindo uma experiência de compra mais interativa e personalizada.','1','2025-01-01 17:30:00'),
(' Realidade Virtual Revoluciona Treinamentos Profissionais e Educação a Distância','noticias/vr.jpg','  A Realidade Virtual (VR) tem se mostrado uma ferramenta poderosa para treinamento e educação em diversos setores, oferecendo uma forma imersiva de aprender e desenvolver habilidades sem sair de casa. Profissionais de áreas como saúde, engenharia e aviação estão se beneficiando de simuladores de VR que reproduzem cenários realistas para treinamento prático.
Hospitais e clínicas, por exemplo, estão utilizando simuladores de VR para treinar médicos e enfermeiros em procedimentos médicos complexos. Isso permite que os profissionais pratiquem técnicas delicadas em um ambiente seguro antes de realizá-las com pacientes reais, reduzindo os riscos e aprimorando a precisão.
 Na educação a distância, a VR está transformando a forma como os alunos interagem com o conteúdo. Universidades e escolas estão investindo em plataformas de aprendizado imersivo que permitem aos alunos participar de aulas e explorar ambientes virtuais como se estivessem fisicamente presentes. Em cursos de história, os alunos podem fazer viagens virtuais a monumentos antigos, enquanto nas ciências, experimentos complexos podem ser realizados de forma interativa.','A Realidade Virtual (VR) tem se mostrado uma ferramenta poderosa para treinamento e educação em diversos setores, oferecendo uma forma imersiva de aprender e desenvolver habilidades sem sair de casa.','1','2025-01-01 17:30:00');
                                                                                                     
                                                                                               
                                                                                                       
                                                                                               
                                                                                                        
                                                                                               
                                                                                          
                                                                                                       
    select * from categoria_noticia;   
     
                                                                                              
 insert into categoria_noticia(noticia_id,categoria_id)
 values(1,1),(2,1),(3,2),(4,2),(5,15),(6,15),(7,14),(8,14),(9,11),(10,11);
                                                                                                        
